[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "0BSD",
  "Unicode-3.0",
  "BSD-3-Clause",
  "MPL-2.0"
]

[[licenses.clarify]]
crate = "ring"
expression = "ISC"
license-files = []

[advisories]
version = 2
ignore = [
  # https://rustsec.org/advisories/RUSTSEC-2023-0071 and
  # https://github.com/ramosbugs/openidconnect-rs/issues/140
  "RUSTSEC-2023-0071",

  # https://rustsec.org/advisories/RUSTSEC-2023-0071
  "RUSTSEC-2023-0071"
]
